### ISSUE TITLE
Incorrect Pisces dates 4/20

### ISSUE THREAD

**Issue by jgiunta1** [micah-akpan/sign-teller#13]
Hey this API is awesome, I think you all did some great work! I just wanted to point out a small issue with the Pisces dates. 

### Summary 
4/20 is registered as Pisces when it should be Taurus. The pisces date range is incorrect compared to the reference docs linked here: https://www.npmjs.com/package/sign-teller/v/3.1.2

See: https://www.horoscope.com/zodiac-signs for correct date ranges

### Steps to reproduce

Run the following with Jest

#### signHelper.js
```javascript
export function getSign(date) {
  const tellSign = require('sign-teller');
  const dateOfBirth = { day: date.getDate(), month: date.getMonth() + 1 };
  return tellSign(dateOfBirth);
}
```

#### signHelper.test.js
```javascript
import {getSign} from '../../src/utils/signHelper.js';
test('Verifies Taurus given March birth date', () => {
  const date = new Date('April 20, 1995 23:15:30');
  console.log(getSign(date));
  expect(getSign(date).sign).toBe("Taurus");
});
```
#### Output
```
    Expected: "Taurus"
    Received: "Pisces"

  console.log
    {
      from: 'March 10',
      to: 'April 20',
      sign: 'Pisces',
      facts: [ 'Creative', 'Sensitive', 'Artistic' ],
      element: 'Water',
      luckyGem: 'Moonstone'
    }
```

**Comment by jgiunta1** [comment]
After setting "type" to tropical I'm actually getting Aries which makes more sense

**Comment by micah-akpan** [comment]
> After setting "type" to tropical I'm actually getting Aries which makes more sense

Okay. @jgiunta1 Thanks for taking the time to try out the library. Feel free to contribute (new features) as you see fit.
